[package]
name = "segway-pid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
egui-macroquad = "0.15.0"
egui = "0.21.0"
basic-http-server = "0.8.1"
